### ISSUE TITLE
Running the model

### ISSUE THREAD

**Issue by saxenarohit** [CPJKU/dcase_task2#3]
How can I run the pre-trained model on a new wav file.

**Comment by dmatte** [comment]
Hi,

If you would like to run the model in an online fashion on a continuous audio stream,
you can find more information [here](https://cpjku.github.io/dcase_task2/#live-audio-tagger).

For offline prediction you can pre-compute the spectrograms of your audio files
analogously to the [prepare_spectrograms.py](https://github.com/CPJKU/dcase_task2/blob/master/dcase_task2/prepare_spectrograms.py) script.

Note that the pre-trained model is trained on spectrograms computed with the flag ```--no_preprocessing```.

Once you have the spectrograms computed
you can predict the respective classes as done in [eval.py](https://github.com/CPJKU/dcase_task2/blob/master/dcase_task2/eval.py).

Best,
Matthias
