### ISSUE TITLE
Can't install the library "madmom.egg"

### ISSUE THREAD

**Issue by 842Mono** [CPJKU/dcase_task2#4]
Hi. I'm trying to get started with running the machine learning model.

When I execute the line `pip install -r requirements.txt` I get:

```
Collecting madmom.egg==info (from -r requirements.txt (line 5))
  Could not find a version that satisfies the requirement madmom.egg==info (from -r requirements.txt (line 5)) (from versions: )
No matching distribution found for madmom.egg==info (from -r requirements.txt (line 5))
```

I'm in a virtual environment and I'm using python2:

```
$ python -V
Python 2.7.15rc1
```

**Comment by dmatte** [comment]
Hi,

I just updated the `requirements.txt` file and hope installing it works now.
If not could you try to just install the required packages manually?

Best,
Matthias

**Comment by 842Mono** [comment]
Hello Matthias. Thank you for your reply. I've pulled the new `requirements.txt`. I'm now getting a new error when it tries to install `madmom`. I've tried it with python and python3.

```
Collecting madmom==0.15.1 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/b7/bb/b9b88d504f5ed3d87dd8a952c4feb37165a96ba1015f912cd4d6f050d75f/madmom-0.15.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Rgd9Rc/madmom/setup.py", line 12, in <module>
        from Cython.Build import cythonize, build_ext
    ImportError: No module named Cython.Build
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Rgd9Rc/madmom/
```

**Comment by superbock** [comment]
Hi, main author of madmom here. The problem is that you also need Cython to install madmom. I am not sure why @dmatte set the required version to 0.15.1, it should also work with newer versions (as far as I can see).

**Comment by 842Mono** [comment]
Hello superbock. Thank you so much! I'm now able to proceed with the setup. I ran:

```
pip install Cython
pip install numpy
```
